# Generated by Django 3.2.4 on 2021-06-26 20:15

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=300)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('student_status', models.BooleanField(default=False)),
                ('landlord_status', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LandLord',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.user')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='landlords/avatar/')),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.user')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='students/avatar/')),
                ('full_name', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('state_of_origin', models.CharField(blank=True, max_length=400)),
                ('university', models.CharField(blank=True, max_length=500)),
                ('department', models.CharField(blank=True, max_length=500)),
                ('facebook_handle', models.CharField(blank=True, max_length=700)),
                ('twitter_handle', models.CharField(blank=True, max_length=700)),
                ('instagram_handle', models.CharField(blank=True, max_length=700)),
                ('personal_interest', models.TextField()),
                ('student_id', models.ImageField(blank=True, null=True, upload_to='students/id/')),
            ],
        ),
    ]
