# Generated by Django 3.2.4 on 2021-06-25 09:31

import bunkie.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=300)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('student_status', models.BooleanField(default=False)),
                ('landlord_status', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', bunkie.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Double Double', 'Double Double'), ('Quad', 'Quad'), ('4 Person', '4 Person'), ('Double', 'Double'), ('Twin', 'Twin'), ('Dorm', 'Dorm')], default='Double', max_length=20)),
                ('description', models.TextField()),
                ('state', models.CharField(blank=True, max_length=400)),
                ('university', models.CharField(blank=True, max_length=500)),
                ('no_of_roommates', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=20)),
                ('type_of_apartment', models.CharField(blank=True, max_length=400)),
                ('price', models.SmallIntegerField()),
                ('rental_period', models.DurationField()),
                ('photo', models.ImageField(blank=True, height_field=100, upload_to='uploads/', width_field=100)),
            ],
        ),
        migrations.CreateModel(
            name='LandLord',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bunkie.user')),
                ('first_name', models.CharField(max_length=300)),
                ('lastname_name', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='landlords/avatar/')),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bunkie.user')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='students/avatar/')),
                ('full_name', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('state_of_origin', models.CharField(blank=True, max_length=400)),
                ('university', models.CharField(blank=True, max_length=500)),
                ('department', models.CharField(blank=True, max_length=500)),
                ('facebook_handle', models.CharField(blank=True, max_length=700)),
                ('twitter_handle', models.CharField(blank=True, max_length=700)),
                ('instagram_handle', models.CharField(blank=True, max_length=700)),
                ('personal_interest', models.TextField()),
                ('student_id', models.ImageField(blank=True, null=True, upload_to='students/id/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='bunkie.room')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='room',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlords', to='bunkie.landlord'),
        ),
    ]
