# Generated by Django 3.2.4 on 2021-06-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunkie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(),
        ),
    ]
