# Generated by Django 3.2.4 on 2021-06-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunkie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, height_field=100, upload_to='uploads/', width_field=100),
        ),
    ]
