# Generated by Django 3.2.4 on 2021-06-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunkie', '0002_auto_20210622_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.SmallIntegerField(),
        ),
    ]
